# Site settings
title: Florian Schlund
description: Software Developer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Florian Schlund
user_description: I'm a Software Engineer from Germany, currently working in the as Java Developer at HUK Coburg.
user_title: Software Engineer
# email: mail@mail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true