title: Florian Schlund
description: Software Engineer
baseurl: ""
url: https://floschl.dev

theme: cvless

# site settings
taglong: My personal site
tagshort: Personal Site

# author settings
author:
  name: Florian Schlund
  email: mail@floschl.dev
photo: assets/files/photo.png

# profile links
profile:
  bluesky: ttps://bsky.app/profile/floschl8.bsky.social
  linkedin: https://linkedin.com/in/florian-schlund
  github: "https://github.com/FloSchl8"

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
